### ISSUE TITLE
Issue-ovveride by server.js

### ISSUE THREAD

**Issue by Epic-SX** [JamesRyo/MERN-admin#10]
Automated Review Comments
Issues in backend/package.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in backend/server.js:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')

**Comment by ghost** [comment]
I got it.
