### ISSUE TITLE
Issue-crm api model added

### ISSUE THREAD

**Issue by Epic-SX** [JamesRyo/MERN-admin#27]
Automated Review Comments
Issues in backend/controllers/adminController.js:
  - (15, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in backend/controllers/authController .js:
  - (1, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in backend/controllers/clientController.js:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in backend/controllers/crudController/crudMethods.js:
  - (32, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
Issues in backend/controllers/crudController/index.js:
  - (3, 'Hardcoded string found')
Issues in backend/controllers/leadController.js:
  - (3, 'Hardcoded string found')
Issues in backend/controllers/orderController.js:
  - (3, 'Hardcoded string found')
Issues in backend/controllers/productController.js:
  - (3, 'Hardcoded string found')
Issues in backend/models/Client.js:
  - (1, 'Hardcoded string found')
Issues in backend/models/Lead.js:
  - (2, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in backend/models/Order.js:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in backend/models/Product.js:
  - (2, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in backend/package-lock.json:
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
Issues in backend/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in backend/routes/api.js:
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')

**Comment by ghost** [comment]
I got it.
