### ISSUE TITLE
Issue-fix controller

### ISSUE THREAD

**Issue by Epic-SX** [JamesRyo/MERN-admin#31]
Automated Review Comments
Issues in backend/controllers/adminController.js:
  - (9, 'Hardcoded string found')
Issues in backend/controllers/clientController.js:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in backend/controllers/crudController/crudMethods.js:
  - (9, 'Hardcoded string found')
Issues in backend/controllers/leadController.js:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in backend/controllers/productController.js:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in frontend/src/components/SidePanel/index.jsx:
  - (13, 'Hardcoded string found')

**Comment by ghost** [comment]
I got it.
