### ISSUE TITLE
Issue-Update README.md

### ISSUE THREAD

**Issue by Epic-SX** [JamesRyo/MERN-admin#39]
Automated Review Comments
Issues in README.md:
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')

**Comment by ghost** [comment]
I got it.
