### ISSUE TITLE
Issue-add comment for demo

### ISSUE THREAD

**Issue by Epic-SX** [JamesRyo/MERN-admin#51]
Automated Review Comments
Issues in backend/controllers/authControllerDemo.js:
  - (1, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
Issues in backend/routes/authApi.js:
  - (9, 'Line exceeds 80 characters')

**Comment by Hroshi405** [comment]
I got it.
