### ISSUE TITLE
Issue-delete & search features fixed

### ISSUE THREAD

**Issue by Epic-SX** [JamesRyo/MERN-admin#57]
Automated Review Comments
Issues in backend/controllers/crudController/crudMethods.js:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in frontend/src/pages/Customer.jsx:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in frontend/src/pages/Product.jsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by Hroshi405** [comment]
I got it.
