### ISSUE TITLE
Issue-Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by Epic-SX** [JamesRyo/MERN-admin#63]
Automated Review Comments
Issues in CONTRIBUTING.md:
  - (2, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')

**Comment by Hroshi405** [comment]
I got it.
